services:
  # ------------------- Postgres -------------------
  postgres:
    image: postgres:15-alpine
    container_name: neetcode-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neetcode
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ------------------- Redis -------------------

  redis:
    image: redis:7-alpine
    container_name: neetcode-redis
    restart: always
    ports:
      - "6379:6379" 

  # ------------------- RabbitMQ -------------------

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: neetcode-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI           
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  

  # ------------------- Primary Backend -------------------

  primary:
    build: 
      context: .
      dockerfile: dockers/dockerfile.primary
    container_name: neetcode-primary
    restart: always
    ports:
      -"3005:3005"
    enviroment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/leetcode
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672  
    depends_on:
      - postgres
      - redis
      - rabbitmq

  # ------------------- Worker -------------------    

  worker:
    build:
      context: .
      dockerfile: dockers/dockerfile.worker
    container_name: neetcode-worker
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@primary:5432/leetcode
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672      
    depends_on:
      - primary
      - redis
      - rabbitmq

  # ------------------- WSS -------------------

  wss:
    build:
      context: .
      dockerfile: docker/Dockerfile.wss
    container_name: leetcode-wss
    restart: always
    ports:
      - "8081:8081"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - worker
      - redis

  # ------------------- Brows -------------------     

  brows:
    build:
      context: .
      dockerfile: docker/Dockerfile.brows
    container_name: leetcode-brows
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - primary

  # ------------------- Volumes -------------------

volumes:
  pgdata:     
  
    